# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Publish

on:
  push:
    branches:
      - unknown
  
  schedule:
     - cron: '52 9 * * *'
     
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04 # 우분투 18.04 에서
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/checkout@v3
      with:
        ref: 'my'
        path: 'my'
    - name: Set up python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install python package
      run: |        
        pip install -r requirements.txt
    
    - name: Install ubuntu package # 우분투 관련 패키지도 설치한 후
      run: |        
        sudo apt-get install fonts-unfonts-core
        sudo apt-get install fonts-unfonts-extra
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add        
        sudo apt-get install google-chrome-stable    
        wget https://chromedriver.storage.googleapis.com/95.0.4638.69/chromedriver_linux64.zip
        unzip ./chromedriver_linux64.zip   
        
    - shell: bash
      env:
        ID: ${{ secrets.ID }}
        PW: ${{ secrets.PASSWORD }}
      run: |
        echo "$ID" >> info.txt
        echo "$PW" >> info.txt
        
    - run: cp -rf my/report_data report_data
        
    - run: tree
      
    - name: Run! # send_to_weather.py 파일을 실행하시오! 
      run: | 
        python ./main.py 
